### ISSUE TITLE
Different Skeletons

### ISSUE THREAD

**Issue by GrigorySamokhin** [PARCO-LAB/FLK#1]
Hello! Thanks for your work!
Im wondering Is there any way to release a train code? As i understand pretrained model can process only minimum number of joints, but it will be really cool to train smpl/smpl-x version.
Thanks in advance

**Comment by DoctorMartins9** [comment]
Hey, thanks for the suggestion! I just uploaded the two scripts to prepare the dataset and train. You can start from there to extend the model to more joints; it should be straightforward!
Let me know if you have any other questions 😃
